const GET_ALL_BREEDS = 'GET_ALL_BREEDS';
const GET_BREED_DETAIL = 'GET_BREED_DETAIL';
const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS'
const FIND_BREED_NAME = 'FIND_BREED_NAME'
const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
const CREATED_BREEDS = 'CREATED_BREEDS';
const CREATE_BREED = 'CREATE_BREED';
const CLEAN_BREED_DETAIL = 'CLEAN_BREED_DETAIL';
const ORDER_AZ = 'ORDER_AZ';
const ORDER_ZA = 'ORDER_ZA';
const ORDER_WEIGHT_ASC = 'ORDER_WEIGHT_ASC';
const ORDER_WEIGHT_DESC = 'ORDER_WEIGHT_DESC';
const BREEDS_DB = 'BREEDS_DB';
const BREEDS_API = 'BREEDS_API';
const FILTER_BY_TEMP = 'FILTER_BY_TEMP'
const SET_PAGE = 'SET_PAGE'

module.exports = {
  GET_ALL_BREEDS,
  GET_BREED_DETAIL,
  GET_ALL_TEMPERAMENTS,
  FIND_BREED_NAME,
  FILTER_TEMPERAMENT,
  CREATE_BREED,
  CREATED_BREEDS,
  CLEAN_BREED_DETAIL,
  ORDER_AZ,
  ORDER_ZA,
  ORDER_WEIGHT_ASC,
  ORDER_WEIGHT_DESC,
  BREEDS_DB,
  BREEDS_API,
  FILTER_BY_TEMP,
  SET_PAGE
}