const GET_ALL_BREEDS = 'GET_ALL_BREEDS';
const GET_BREED_DETAIL = 'GET_BREED_DETAIL';
const CREATE_BREED = 'CREATE_BREED';
const FIND_BREED_NAME = 'FIND_BREED_NAME'
const FILTER_TEMPERAMENT = 'FILTER_TEMPERAMENT';
const ORDER_AZ = 'ORDER_AZ';
const ORDER_ZA = 'ORDER_ZA';
const ORDER_WEIGHT_ASC = 'ORDER_WEIGHT_ASC';
const ORDER_WEIGHT_DESC = 'ORDER_WEIGHT_DESC';

module.exports = {
  GET_ALL_BREEDS,
  GET_BREED_DETAIL,
  CREATE_BREED,
  FIND_BREED_NAME,
  FILTER_TEMPERAMENT,
  ORDER_AZ,
  ORDER_ZA,
  ORDER_WEIGHT_ASC,
  ORDER_WEIGHT_DESC
}